### ISSUE TITLE
Social sharing icons

### ISSUE THREAD

**Issue by mickaudio** [MikeiLL/think-peace-client#1]
we need to kinda figure out...

1. Brief description
2. Content for a Facebook banner

**Comment by mickaudio** [comment]
Updated copy:

A MMOPN (Massively Multiuser Online Peace Network) for capturing and communicating peace. Each wish in Think Peace ignites dynamic displays of music, art and vibration…and then fades away after 24 hours.

**Comment by MikeiLL** [comment]
Close this issue?
