### ISSUE TITLE
About Think Peace - copy

### ISSUE THREAD

**Issue by mickaudio** [MikeiLL/think-peace-client#2]
————

About Think Peace

In the range of human expression and experiences, peace is an advanced concept. It is also less durable; folks in the know understand this and find ways to activate peace inside and outside every day...like Ringo, who has been sending reminders for so long, his peace sign shoots into the air the second he sees a camera.

We call them demonstrations for a reason.

Activate your own peace today, then give it away. Do it again tomorrow.

A note: Each wish in Think Peace ignites dynamic displays of music, art, and vibration, and then fades away after 24 hours.

————

Credits

Scott Anthony - Founder
Abby Strugger - Art director
Mike iLL - Technical design
Chris Angelico - Technical design
Faith Ekanem - Technical design
Oreoluwa Muzzamil - Technical design
Rebecca Turner - Copywriter

————

Help support our talented designers, by Venmoing here:
(Venmo link for @storybooksound)

————

(Github Open Source copy here)

**Comment by MikeiLL** [comment]
@mickaudio what do you link about something like:
 Think Peace is a project of <a href="https://www.storybooksound.com" target="_blank" className="text-white underline">Storybook Sound</a>, a creative studio that makes music, art, and experiences that inspire and connect people.

**Comment by mickaudio** [comment]
That’s really nice…we have a preference of it at the bottom of credits, but leave to you.

**Comment by MikeiLL** [comment]
In-progress. Want's some refining.
