### ISSUE TITLE
Let’s attack Florida (first event)

### ISSUE THREAD

**Issue by mickaudio** [MikeiLL/think-peace-client#20]
Visitors say they love, but are somewhat baffled by the app

i would like @MikeiLL to create a peace demonstration for Florida that addresses black voices or gay and trans rights.

this will complete the picture of what the app is for, and create the means to ingest new demonstations of music and art

**Comment by mickaudio** [comment]
Like the default fireflies, one layer of dynamics would be ok, but at least a second layer of music or art would be an amazing achievement for the app

**Comment by MikeiLL** [comment]
@mickaudio Did you close this on purpose?

**Comment by mickaudio** [comment]
Yeah, definitely scope creep and not an issue.On Feb 8, 2023, at 4:43 PM, Mike iLL Kilmer ***@***.***> wrote:﻿
@mickaudio Did you close this on purpose?
